// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBno2GSk4ZAb88KzcFAe9cpRJbK7lt9zdM',
    appId: '1:279122252609:web:ca386b04a64cd24c1747c0',
    messagingSenderId: '279122252609',
    projectId: 'fallguard-8e840',
    authDomain: 'fallguard-8e840.firebaseapp.com',
    storageBucket: 'fallguard-8e840.firebasestorage.app',
    measurementId: 'G-JKTXJXYRY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4vDCk15pjyHvSTs2AQ_cLwp0QbbO4p4I',
    appId: '1:279122252609:android:4a661c22b931c37e1747c0',
    messagingSenderId: '279122252609',
    projectId: 'fallguard-8e840',
    storageBucket: 'fallguard-8e840.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpZGzqYMj2NlcVZW5XYwyRwu4P9drc_xs',
    appId: '1:279122252609:ios:4b41c8742b3558851747c0',
    messagingSenderId: '279122252609',
    projectId: 'fallguard-8e840',
    storageBucket: 'fallguard-8e840.firebasestorage.app',
    iosClientId: '279122252609-0mdeq8r06err9vmm970qbck06n46fl35.apps.googleusercontent.com',
    iosBundleId: 'com.fallguard.fallguard',
  );
}
